#pragma once

enum class NodeType
{
    PROGRAM,
    GLOBAL_LIST,
    GLOBAL,
    DECLARATION,
    VARIABLE_LIST,
    VARIABLE,
    ARRAY_DECLARATION,
    ARRAY_INDEXING,
    FUNCTION,
    PARAMETER_LIST,
    STATEMENT,
    BLOCK,
    DECLARATION_LIST,
    STATEMENT_LIST,
    ASSIGNMENT_STATEMENT,
    RETURN_STATEMENT,
    PRINT_STATEMENT,
    PRINT_LIST,
    PRINT_ITEM,
    BREAK_STATEMENT,
    RELATION,
    ARGUMENT_LIST,
    EXPRESSION_LIST,
    EXPRESSION,
    IDENTIFIER_DATA,
    INT_DATA,
    FLOAT_DATA,
    STRING_DATA
};