name: Merge with main
on: 
  workflow_run:
    workflows:
      - "C/C++ CI"
      - "CodeQL"
    types:
      - completed
    branches:
      - '!main'
jobs:
  merge-with-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge staging -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}